// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7SgDJas_OvcA_id1s9P9-tkUnfB8RkM',
    appId: '1:320521350983:web:4ef01ce87fa6db62262662',
    messagingSenderId: '320521350983',
    projectId: 'tourism-app-9529a',
    authDomain: 'tourism-app-9529a.firebaseapp.com',
    storageBucket: 'tourism-app-9529a.firebasestorage.app',
    measurementId: 'G-F787XVND7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqNwUVZ5CZfcgB8mO38bsdKxTsN8ote8',
    appId: '1:320521350983:android:7936b7e4be913f9a262662',
    messagingSenderId: '320521350983',
    projectId: 'tourism-app-9529a',
    storageBucket: 'tourism-app-9529a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzneOV3V5n5Axpz8InfDqfYYVxe4kXL9E',
    appId: '1:320521350983:ios:e00b7527c7f4c90a262662',
    messagingSenderId: '320521350983',
    projectId: 'tourism-app-9529a',
    storageBucket: 'tourism-app-9529a.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzneOV3V5n5Axpz8InfDqfYYVxe4kXL9E',
    appId: '1:320521350983:ios:e00b7527c7f4c90a262662',
    messagingSenderId: '320521350983',
    projectId: 'tourism-app-9529a',
    storageBucket: 'tourism-app-9529a.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi7SgDJas_OvcA_id1s9P9-tkUnfB8RkM',
    appId: '1:320521350983:web:567b44e9a86aa9f3262662',
    messagingSenderId: '320521350983',
    projectId: 'tourism-app-9529a',
    authDomain: 'tourism-app-9529a.firebaseapp.com',
    storageBucket: 'tourism-app-9529a.firebasestorage.app',
    measurementId: 'G-LNEJN7VM5F',
  );
}
